# PROJECT: cube
[cube]
lang = "C++"

cpp.std = 14
cpp.compiler = "clang++"

build.type = "executable"
build.dir = "./build"

src = "./src"
env = "./.env"

[cube.compiler]

debug.optimization = 0
debug.defines = [
    "YMAKE_DEBUG",
    "YMAKE_TEST=1"
]

# compiler flags.
debug.flags = [
    "-Wall",
    "-g"
]

release.optimization = 3
release.defines = [
    "DNDEBUG",
]