# PROJECT: NewTest

[NewTest]
version = "0.1.0"

lang = "C++"
cpp.std = 14
cpp.compiler = "clang++"

build.type = "executable"
build.dir = "./build"

src = "./src"

includes = [
    "./src",
    "./include/NewTest"
]

[NewTest.compiler]

defines.debug = [
    "NT_DEBUG"
]

optimization.release = 3
defines.release = [
    "NT_NDEBUG"
]